"""
Agent 2 — Validation Agent
Responsible for:
  - Receiving the response generated by the Retrieval Agent
  - Checking whether the response is grounded in the retrieved context
  - Returning a verdict: GROUNDED, PARTIALLY_GROUNDED, or UNVERIFIABLE

This is the guardrail agent. It makes one LLM call to verify
the response against the source context, without generating new content.
"""
import os
from openai import OpenAI
from dotenv import load_dotenv
import logging

load_dotenv()

client = OpenAI(
    api_key=os.environ.get("GROQ_API_KEY"),
    base_url="https://api.groq.com/openai/v1"
)

MODEL  = "llama-3.3-70b-versatile"
logger = logging.getLogger("policy_assistant")

VERDICTS = ("GROUNDED", "PARTIALLY_GROUNDED", "UNVERIFIABLE")


def run(response: str, context: str, query: str) -> dict:
    """
    Validate whether the response is grounded in the retrieved context.

    Args:
        response: The response generated by the Retrieval Agent
        context:  The retrieved policy chunks used as context
        query:    The original user query

    Returns:
        dict with keys: verdict, reason, agent
    """
    # Skip validation for fallback responses — nothing to validate
    if not response or "couldn't find" in response.lower():
        return {
            "verdict": "UNVERIFIABLE",
            "reason":  "No response was generated to validate.",
            "agent":   "validation_agent"
        }

    prompt = f"""You are a strict fact-checker. Your only job is to verify if the response is supported by the context.

Context (retrieved policy chunks):
{context}

User query: {query}

Response to validate:
{response}

Check if the response is factually supported by the context above.
Reply with EXACTLY one of these verdicts on the first line:
GROUNDED — the response is fully supported by the context
PARTIALLY_GROUNDED — the response is mostly correct but contains minor additions or paraphrasing not in the context
UNVERIFIABLE — the response contains claims not found in the context

Then on the next line write: Reason: (one short sentence explaining your verdict)

Do not add anything else."""

    try:
        api_response = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            max_tokens=150
        )
        raw = api_response.choices[0].message.content.strip()
        lines = [l.strip() for l in raw.splitlines() if l.strip()]

        # Parse verdict from first line
        verdict = "UNVERIFIABLE"
        for v in VERDICTS:
            if lines[0].startswith(v):
                verdict = v
                break

        # Parse reason from second line
        reason = lines[1].replace("Reason:", "").strip() if len(lines) > 1 else "No reason provided."

        logger.info(
            f"[VALIDATION] verdict=\"{verdict}\" query=\"{query}\""
        )

        return {
            "verdict": verdict,
            "reason":  reason,
            "agent":   "validation_agent"
        }

    except Exception as e:
        logger.error(f"[VALIDATION_ERROR] {e}")
        return {
            "verdict": "UNVERIFIABLE",
            "reason":  "Validation could not be completed.",
            "agent":   "validation_agent"
        }
